[package]
name = "zalymo/librarian"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"node_modules",
	"DevPackages",
	"sourcemap.json",
	"bin",
	"include",
	"out",
	"package-lock.json",
	"test-runner-scripts",
	"dev.project.json",
	"test.project.json",
]

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"